package com.teacherhub.risk.enums;

public enum RiskTagCode {

    EMOTIONAL_EXPRESSION,
    PERSONAL_ATTACK,
    THREAT,
    LEGAL_ADMINISTRATIVE_ACTION,
    PUBLIC_DISCLOSURE_THREAT,
    REPETITION,
    UNREASONABLE_DEMAND,
    PERSONAL_INFORMATION_RISK
}